### ISSUE TITLE
Typo in Valkurm Dunes map

### ISSUE THREAD

**Issue by ConteAlmaviva** [Moophorizon/ffxi-remapster-labeled#3]
"Valkrum Emperor" -> "Valkurm Emperor"

**Comment by Moophorizon** [comment]
Should be fixed now, Thank you!

**Comment by ConteAlmaviva** [comment]
Thanks much!  Maps are lovely, by the way ^^

**Comment by Moophorizon** [comment]
Thanks! And I just finished catching up the 1024x1024 so if you don't like the hiccups in korroloka and places, try those out!
