### ISSUE TITLE
Project abandoned?

### ISSUE THREAD

**Issue by polishgerbils** [Moophorizon/ffxi-remapster-labeled#6]
Was this project abandoned? Looked forward each week to the new updates but I see there hasn't been an update in about a month. Would be a shame if this wasn't completed as these are by far the best looking maps.

**Comment by war3zlod3r** [comment]
I also keep checking back regularly and the upgrades have made a big impact on the way I play. Would love to see this project continue or help out if I can some way!

**Comment by Moophorizon** [comment]
I'll start working on it again, sorry for the delay!
