### ISSUE TITLE
Sky Maps requst

### ISSUE THREAD

**Issue by TwistedAx** [Moophorizon/ffxi-remapster-labeled#7]
this is a request, rather than an issue.

could you pleae update the sky maps to have more thorough pathing and god information like the older detailed maps, in a similar style to the sky maps from RadialArcana on FFXIAH? or make it an optional?
https://www.ffxiah.com/forum/topic/55110/updated-map-mods-2020/

this would be a massive upgrade to the current remapster sky maps

please and thank you

p.s ; these labeled maps are truely a thing of beauty, thank you for redoing them with such detailed information

**Comment by polishgerbils** [comment]
> 

I made this map for my own purposes. Msg me at Mimi#5106 if you are interested in the .dat file.

https://i.imgur.com/3CXOocQ.jpg

**Comment by Moophorizon** [comment]
![ruaun_gardens](https://github.com/Moophorizon/ffxi-remapster-labeled/assets/122415905/47acc676-489b-4071-b72d-3d762db495cf)

I'll upload 1024 and 2048 versions
